# unix-home bashrc project

if [ -f /etc/bashrc ]; then
	source /etc/bashrc
fi

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# unlimited command history
HISTSIZE=
HISTFILESIZE=

# add time stamp for history command
HISTTIMEFORMAT="%Y-%m-%d %T  "

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

umask 077

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	. /etc/bash_completion
fi

# Needs to know MY_RC_HOME first
source ~/.site_env/bash/my_rc_home.sh

# Auxiliary scripts
__source_repo_rc() {
    local rcfile
    if [ -d $MY_RC_HOME/bashrc.d ]; then
        for rcfile in $MY_RC_HOME/bashrc.d/*.sh ; do
            if [ -r "$rcfile" ]; then
                . "$rcfile"
            fi
        done
    fi
}
__source_repo_rc

if __has tmux; then
    if [ "$FORCE_TMUX" = yes ] && [ -z "$TMUX" ]; then
        exec tmux new -As main
    elif [ "$FORCE_TMUX" = no ]; then
        :
    elif [ "$AUTO_ATTACH_TMUX" = yes ] && [ "$TMUX_ATTACHED" != yes ] && [ -n "$SSH_CONNECTION" ]; then
        exec tmux new -As main
    fi
fi

PROMPT_COMMAND=__do_after_command
trap __do_before_command DEBUG

# vim: set ft=sh:

