#!/bin/sh

readonly version_str=$(cd "$MY_RC_HOME" && git describe || echo "(unknown version)")
readonly output_width=78

header() {
    echo "[1m* $*[0m"
}

less -r << EOF
============================[ H O M E  I N F O ]==============================
$(printf "%${output_width}s" "$version_str")

$(header Available commands and aliases)

    helloworld <language>
        Give a simple hello-world template for the given language.

    connect connect-tmux connect-no-tmux
        ssh onto a server, chaining the hostname in the command prompt.
        tmux can be forced on/off using the dashed variants.

    bashtrap
        While true, do bash. Don't be scared --- you have your way out.

    -   cd ..
    t   Attach to session "main" in tmux. Create if not exist.
    c   Attach to session "main" in GNU screen. Create if not exist.
    b   '<expression>'
        Quick calculator using GNU bc.

$(header Modified commands)

    cd      auto ls and remember 10 cd histories
    cd --   print cd history
    cd -#   cd into history item '#'
    git     aliased to hub, if available
    make    recursively find makefiles in parent directories.

$(header Useful functions in "$HOME/.site_env/bash/*.sh")

    __has <program>
        Check if "program" is available on your system. NO stdout/stderr.
        Returns 0 if program is available, otherwise 1.

        Example:
            __has program && alias prog='program --a-long-parameter'

    __do_once
        Check if the current line is already sourced. If yes, return 1,
        otherwise return 0. Useful for one-time appending a variable.

        Example:
            __do_once && export PATH=\$PATH:/path/to/somewhere

$(header Special variables)

    BASH_PS1_HOSTNAME     - Force using this as hostname info in the prompt.
    AUTO_ATTACH_TMUX      - Exec tmux automatically upon a remote login.
                          - Valid options: yes, no (default).

    MY_FMT_PS1_HOSTNAME_ROOT         | - Override terminal color/format for
    MY_FMT_PS1_HOSTNAME              |   bash PS1 prompt. Currently please
    MY_FMT_PS1_USERNAME_ROOT         |   use ansi terminal control characters
    MY_FMT_PS1_USERNAME              |   or tput instructions.
    MY_FMT_PS1_HOSTCHAIN_DECOR_ROOT  |
    MY_FMT_PS1_HOSTCHAIN_DECOR       | - Example:
    MY_FMT_PS1_IFS                   |
    MY_FMT_PS1_IFS_VALUE             |   MY_FMT_PS1_CWD=\$'\033[32m'
    MY_FMT_PS1_CHROOT_ROOT           |   will change the PWD section to color
    MY_FMT_PS1_CHROOT                |   green in most color terminals.
    MY_FMT_PS1_BG_INDICATOR          |
    MY_FMT_PS1_SHLVL_INDICATOR       |   MY_FMT_STATUS_OK=\$(tput bold)
    MY_FMT_PS1_SCREEN_INDICATOR      |   will use bold fonts for the status
    MY_FMT_PS1_GIT_INDICATOR         |   line.
    MY_FMT_PS1_CWD                   |
    MY_FMT_PS1_PHYSICAL_CWD          |   MY_FMT_STATUS_ERROR= (line contd.)
    MY_FMT_PS1_DOLLAR_HASH           |       \$(tput smul)\$(tput setaf 2)
    MY_FMT_STATUS_OK                 |   will use a combined format: underline
    MY_FMT_STATUS_ERROR              |   and color green.
    MY_FMT_STATUS_HRULE              |
    MY_FMT_CMD_EXPANSIONS            |
    MY_FMT_FORCE_NEWLINE             |

    MY_BASH_THICK_SEPARATOR          | - Use an extra line to display the
    MY_BASH_THICK_SEPARATOR_CHAR     |   separator rather than underscored
                                     |   terminal character effect which is
                                     |   not so-widely supported.
                                     |
                                     |   MY_BASH_THICK_SEPARATOR is enabled if
                                     |   terminal 'linux' is observed, or could
                                     |   be forced by setting to 'yes'. Default
                                     |   char used in the separator is '~'.

    MY_BASH_ENABLE_HOSTCHAIN         | - Enables host chain, command expansion,
    MY_BASH_ENABLE_CMD_EXPANSION     |   status line.
    MY_BASH_ENABLE_STATUS_LINE       |   Valid options: yes (default), no.

    PS1   - Now it's fully revised. Try echo "\$PS1" to see how to customize.

    BASH_CMD_EXPANSION_SINK - Controls the target when printing command 
            expansion. Default is the standard error fd: &2. Acceptable
            formats are: "/path/to/a/writtable/file" or &N where N is an open
            file descriptor).

    BASH_CMD_EXPANSION_SINK_PROXY_FD - The temporary allocated file descriptor
            used to relay the command expansion string. Default value: 99.

$(header Site specific configuration files \(NOT in version control\))

    $HOME/.site_env/bash/*.sh       - *deperacated*.
    $HOME/.site_env/bash/*@pre.sh   - sourced before major setup.
    $HOME/.site_env/bash/*@post.sh  - sourced after major setup.

    $HOME/.site_env/csh/*.csh
    $HOME/.site_env/vim/*.vim
    $HOME/.site_env/git/gitconfig
    $HOME/.site_env/tmux/tmux.conf
    $HOME/.site_env/exec/*

$(printf "%${output_width}s" "$version_str")
----------------------------------[ E N D ]-----------------------------------
EOF
