#!/bin/bash

if [ "$#" = 0 ]; then
    raw_input="$(xsel)"
else
    raw_input="$*"
fi

word=$(echo "$raw_input" | xargs | sed -e 's/ /-/g' | tr '[:upper:]' '[:lower:]')
urlhead='http://www.merriam-webster.com/dictionary'

[ -n "$word" ] && exec xdg-open "$urlhead/$word" &>/dev/null

# vim: set ft=sh:

