#!/bin/sh

client_is_wide_enough() {
    test "$(tmux display-message -p '#{client_width}')" -ge 100
    return $?
}

if [ "$1" = "window-status-active" ]; then
    if client_is_wide_enough; then
        command tmux display-message -p '#I%%#P[#{pane_width}x#{pane_height}]:#W(#{pane_pid})#F'
    else
        command tmux display-message -p '[#I:#W]#F'

    fi
    exit 0
fi

if [ "$1" = "window-status-inactive" ]; then
    if client_is_wide_enough; then
        command tmux display-message -p '[#I:#W]#F'
    else
        command tmux display-message -p '[#I]#F'
    fi
    exit 0
fi

if [ "$1" = "date" ]; then
    if client_is_wide_enough; then
        command tmux display-message -p '%a %m/%d/%Y'
    else
        command tmux display-message -p '%m/%d'
    fi
    exit 0
fi

if [ "$1" = "system-load" ]; then
    if client_is_wide_enough; then
        echo "Load $(system-info --loadavg-1min)"
    else
        echo "L$(system-info --loadavg-1min)"
    fi
    exit 0
fi

exit 1

